---

- name: Install LogRhythem Agent from repo
  package: name={{logrhythm_package}}
  when: "'.deb' not in logrhythm_package"

- name: Install LogRhythm Agent from .deb package
  apt: deb={{logrhythm_package}}
  when: "'.deb' in logrhythm_package"

- name: Remove scsm init script (breaks over ssh connections)
  file:
      state: absent
      path: /etc/init.d/scsm

- name: Copy /etc/init/scsmd.conf
  copy:
      src: scsmd_upstart
      dest: /etc/init/scsmd.conf
      mode: 0644
      owner: root
      group: root

- name: Update scsm.ini
  template:
      src: scsm.ini.j2
      dest: /opt/logrhythm/scsm/config/scsm.ini
      mode: 0600
      owner: root
      group: root
  notify: restart scsmd

- name: Ensure scsm is started
  service: name=scsmd state=started enabled=yes
